# Generated by Django 4.2.10 on 2024-02-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0002_alter_persona_tipousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=7),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
