# Generated by Django 4.2.10 on 2024-02-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0003_alter_movimientoinventario_tipo_movimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='ultimoConteo',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
