# Generated by Django 4.2.10 on 2024-02-28 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0004_movimientoinventario_ultimoconteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='depot.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioCompra',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioUnitario',
            field=models.PositiveIntegerField(),
        ),
    ]
