# Generated by Django 4.2.10 on 2024-03-04 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0005_alter_movimientoinventario_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.PositiveIntegerField()),
                ('vrUnitario', models.PositiveIntegerField()),
                ('cantidad', models.PositiveBigIntegerField()),
                ('total', models.PositiveBigIntegerField()),
                ('stockAntes', models.PositiveBigIntegerField()),
                ('stockDespues', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=7)),
                ('tipoProceso', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=7)),
                ('numeroDocumento', models.CharField(blank=True, default=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='depot.empresa')),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precioUnitario',
            new_name='precioVenta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MovimientoInventario',
        ),
        migrations.AddField(
            model_name='detalledocumento',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docCount', to='depot.documento'),
        ),
        migrations.AddField(
            model_name='detalledocumento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockCount', to='depot.producto'),
        ),
    ]
