# Generated by Django 4.2.10 on 2024-03-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0006_detalledocumento_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipoProceso',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatico', 'Automatico')], max_length=12),
        ),
    ]
