# Generated by Django 4.2.10 on 2024-03-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0008_proveedor_documento_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalledocumento',
            name='descuento',
        ),
        migrations.AddField(
            model_name='detalledocumento',
            name='unidad',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
    ]
