# Generated by Django 4.2.10 on 2024-03-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0009_remove_detalledocumento_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedida',
            name='abreviatura',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
