# Generated by Django 4.2.10 on 2024-04-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0010_unidadmedida_abreviatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre_auxiliar',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
    ]
