# Generated by Django 4.2.10 on 2024-04-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0011_producto_nombre_auxiliar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_auxiliar',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
